name: CI/CD - Build & Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test

      # Step 5: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/nodejs-demo-app:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/nodejs-demo-app:${{ github.sha }}

      # Step 7: Output success message
      - name: Show pushed image info
        run: echo "✅ Image pushed to ghcr.io/${{ secrets.GHCR_USERNAME }}/nodejs-demo-app:latest"
